export global Palette {
    // warna solid
    in-out property <color> bg: #141415;
    in-out property <color> surface: #31343F;
    in-out property <color> text: #E9E6DD;
    in-out property <color> muted: #73838B;
    in-out property <color> accent: #ffffff;
    in-out property <color> ancent-hover: #585758;
    in-out property <color> bg_surface_1: #2d2c33;
    in-out property <color> bg_surface_2: #2a2a30;
    in-out property <color> bg_surface_hover: #26262B;
    in-out property <color> border: #212125;
    in-out property <color> text_primary: #EEEAF9;
    in-out property <color> text_secondary: #B7B2C6;
    in-out property <color> icon_default: #7C7888;
    in-out property <color> icon_hover: #CFCBDD;
    in-out property <color> selected_container: #1E1D22;
    in-out property <color> success: #4CAF50;
    in-out property <color> error: #F44336;
}
